### ISSUE TITLE
Weird cyrillic Щ capital letter in Bold and Bold Italic in version 4.106

### ISSUE THREAD

**Issue by molumen** [mozilla/Fira#139] opened 2016-01-14 11:27 UTC
Since version 4.106 came out, the Cyrillic bold capital letter Щ is incorrect. The small descender must me located on the right side, but it instead is located in the centre of the letter.

Here is how it looked in version 3.111 (correct):
![screen shot 2016-01-14 at 14 28 16](https://cloud.githubusercontent.com/assets/8453676/12323227/be956c32-baca-11e5-99af-0b1453827756.png)

Here's how it looks now in version 4.106 (incorrect):
![screen shot 2016-01-14 at 14 24 23](https://cloud.githubusercontent.com/assets/8453676/12323161/35ec364a-baca-11e5-8c88-79d68fb3bd55.png)

**Comment by alexeyten** [comment] 2016-01-14 11:56
could be duplicate of #121

**Comment by molumen** [comment] 2016-01-14 12:53
@alexeyten Yes, I didn't see the previous report from October 2015. Is there a way I can delete this one so there are no duplicate reports of the same bug?

**Comment by patrykdesign** [comment] 2016-01-15 20:51
Yes dup if #121

**Closed by patrykdesign** 2016-01-15 20:51 UTC

**Comment by Colia** [comment] 2016-12-08 12:20
??

**Comment by Colia** [comment] 2016-12-08 12:20
??? still the same issue
