### ISSUE TITLE
OpenType layout tables differ between OTF and TTF versions

### ISSUE THREAD

**Issue by jfkthame** [mozilla/Fira#82] opened 2015-05-12 16:04 UTC
Comparing the GPOS tables in FiraSans 4.101, there are a number of differences that will result in unexpected discrepancies in behavior between the two font formats.

Testcase: http://people.mozilla.org/~jkew/tests/Fira4101/FiraTest.html

This example displays the same character sequences using both the OTF and TTF versions of the font. Note the different results!

**Comment by patrykdesign** [comment] 2015-05-13 21:05
@carrois can you please comment? wouldn't want to push in v.4.101 yet if this is infact a bug.

**Comment by jfkthame** [comment] 2015-05-19 13:33
This issue is still present in the most recent Fira 4.102 files.

Testcase (with updated fonts as of today): http://people.mozilla.org/~jkew/tests/Fira4102/FiraTest.html

**Comment by jfkthame** [comment] 2015-05-27 10:24
Still broken in 4.103 today. Note that issue 85 shows a real-world example where the mismatch in OpenType support means the OTF release is broken even though the TTF version works.

**Comment by jfkthame** [comment] 2015-05-27 10:51
Note that this issue also affects Fira Mono -- there are discrepancies in the OpenType layout behavior between OTF and TTF versions. Because of the smaller character set, there aren't as many examples to be found, but U+037A and U+1FBE are a couple of (Greek) characters that show behavioral differences.

**Comment by jfkthame** [comment] 2015-06-09 10:22
In the Fira Mono fonts from https://github.com/mozilla/Fira/issues/56#issuecomment-110300061, there is no longer any discrepancy between the OpenType features in OTF and TTF files, afaics.

@carrois @schriftgestalt We still need to check whether this is resolved for Fira Sans, with its richer character set and more extensive OpenType tables.

**Comment by patrykdesign** [comment] 2015-07-30 18:54
@jfkthame this should be fixed with 4.105 now, can you confirm?
I can confirm 4.105 fixed https://github.com/mozilla/Fira/issues/85 which seemed related.

**Comment by patrykdesign** [comment] 2015-08-10 21:51
Tested with Fira 4.105 using @jfkthame test v.4.104 test file and looks like its fixed now.
![screen shot 2015-08-10 at 5 49 53 pm](https://cloud.githubusercontent.com/assets/1503049/9185270/6392fc04-3f88-11e5-8329-36ceafce10fd.png)

**Closed by patrykdesign** 2015-08-10 21:51 UTC
